"""Add BetaTester table

Revision ID: 488fcc132f16
Revises: 7c87b65e2e33
Create Date: 2025-04-03 07:39:26.238872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488fcc132f16'
down_revision: Union[str, None] = '7c87b65e2e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_testers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beta_testers_email'), 'beta_testers', ['email'], unique=True)
    op.create_index(op.f('ix_beta_testers_id'), 'beta_testers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beta_testers_id'), table_name='beta_testers')
    op.drop_index(op.f('ix_beta_testers_email'), table_name='beta_testers')
    op.drop_table('beta_testers')
    # ### end Alembic commands ###
